from graphviz import Digraph
dot = Digraph()
dot.attr('node', fontname='SimSun')
dot.node('A', 'Start of heapsort')
dot.node('B', 'for (int i = 0; i < a.length; i++)')
dot.node('C', 'for (int j = i * 3 + 1; j < i * 3 + 4; j++)')
dot.node('D', 'if (j < a.length)')
dot.node('E', 'if (a[j] < a[i])')
dot.node('F', 'switchPos(a, i, j)')
dot.node('G', 'heapsort(a)')
dot.node('H', 'End of heapsort')
dot.edge('A', 'B')
dot.edge('B', 'C', label='i < a.length (true)')
dot.edge('C', 'D', label='j < i * 3 + 4 (true)')
dot.edge('D', 'E', label='j < a.length (true)')
dot.edge('E', 'F', label='a[j] < a[i] (true)')
dot.edge('F', 'G')
dot.edge('G', 'C')
dot.edge('E', 'C', label='a[j] >= a[i] (false)')
dot.edge('D', 'C', label='j >= a.length (false)')
dot.edge('C', 'B', label='j >= i * 3 + 4 (false)')
dot.edge('B', 'H', label='i >= a.length (false)')
dot.render('../graph', format='png', view=False)